category:
  highest_level: 1
  middle_level: 2
  lowest_level: 3
blog_category:
  news: 1
limit:
  blog_home_page: 4
  product_field: 10
  related_products: 4
  new_products: 3
  paginate:
    products: 12
    blogs: 5
    documents: 10
    videos: 10
  menu_block:
    a_to_z: 3.0
    brand: 4.0
  label_block: 10
format:
  created_at: "%d/%m/%Y"
media_type:
  document: 0
  video: 1
